# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "phi-3-onnx"
python_version = "3.11"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
cmake = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
numpy = "2.1.3"
onnxruntime-genai = "0.5.2"
tiktoken = "0.8.0"
tqdm = "4.67.1"

# [[git]]
# from_source = "{{git_source_url}}"
# to_destination = "{{git_destination_dir}}"
# branch = "{{branch_name}}"
# requirements_file = "requirements.txt"
# setup_commands = [
#   "{{setup_command}}"
# ]

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-onnx/custom.json"
to_destination = "custom.json"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-onnx/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-onnx/device.sh"
to_destination = "device.sh"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "device.sh"